config/routes.rb
Blog::Application.routes.draw do

  root :to => "home#index"

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :participants
  resources :animals
  resources :comments
  resources :articles do 
	resources:comments
  end

end

app/models/participant.rb
class Participant < ActiveRecord::Base
 
 def self.table_name
    "participants"
 end

 attr_accessible :created_at, :cs1, :cs10, :cs11, :cs12, :cs13, :cs14, :cs15, :cs2, :cs3, :cs4, :cs5, :cs6, :cs7, :cs8, :cs9, :current_sign_in_at, :email, :first_name, :id, :illustration, :last_name, :last_sign_in_ip, :name, :passcode, :score, :session_id, :sign_in_count, :signature, :table_number, :updated_at, :virtual_table_id

end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @participants }
    end
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
    @participant = Participant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/new
  # GET /participants/new.json
  def new
    @participant = Participant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/1/edit
  def edit
    @participant = Participant.find(params[:id])
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(params[:participant])

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render json: @participant, status: :created, location: @participant }
      else
        format.html { render action: "new" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /participants/1
  # PUT /participants/1.json
  def update
    @participant = Participant.find(params[:id])

    respond_to do |format|
      if @participant.update_attributes(params[:participant])
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy

    respond_to do |format|
      format.html { redirect_to participants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_for(@participant) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @participant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :passcode %><br />
    <%= f.text_field :passcode %>
  </div>
  <div class="field">
    <%= f.label :sign_in_count %><br />
    <%= f.text_field :sign_in_count %>
  </div>
  <div class="field">
    <%= f.label :current_sign_in_at %><br />
    <%= f.text_field :current_sign_in_at %>
  </div>
  <div class="field">
    <%= f.label :last_sign_in_at %><br />
    <%= f.text_field :last_sign_in_at %>
  </div>
  <div class="field">
    <%= f.label :current_sign_in_ip %><br />
    <%= f.text_field :current_sign_in_ip %>
  </div>
  <div class="field">
    <%= f.label :last_sign_in_ip %><br />
    <%= f.text_field :last_sign_in_ip %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.text_field :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br />
    <%= f.text_field :updated_at %>
  </div>
  <div class="field">
    <%= f.label :illustration %><br />
    <%= f.text_field :illustration %>
  </div>
  <div class="field">
    <%= f.label :table_number %><br />
    <%= f.text_field :table_number %>
  </div>
  <div class="field">
    <%= f.label :session_id %><br />
    <%= f.text_field :session_id %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.text_field :score %>
  </div>
  <div class="field">
    <%= f.label :signature %><br />
    <%= f.text_field :signature %>
  </div>
  <div class="field">
    <%= f.label :virtual_table_id %><br />
    <%= f.text_field :virtual_table_id %>
  </div>
  <div class="field">
    <%= f.label :cs1 %><br />
    <%= f.text_field :cs1 %>
  </div>
  <div class="field">
    <%= f.label :cs2 %><br />
    <%= f.text_field :cs2 %>
  </div>
  <div class="field">
    <%= f.label :cs3 %><br />
    <%= f.text_field :cs3 %>
  </div>
  <div class="field">
    <%= f.label :cs4 %><br />
    <%= f.text_field :cs4 %>
  </div>
  <div class="field">
    <%= f.label :cs5 %><br />
    <%= f.text_field :cs5 %>
  </div>
  <div class="field">
    <%= f.label :cs6 %><br />
    <%= f.text_field :cs6 %>
  </div>
  <div class="field">
    <%= f.label :cs7 %><br />
    <%= f.text_field :cs7 %>
  </div>
  <div class="field">
    <%= f.label :cs8 %><br />
    <%= f.text_field :cs8 %>
  </div>
  <div class="field">
    <%= f.label :cs9 %><br />
    <%= f.text_field :cs9 %>
  </div>
  <div class="field">
    <%= f.label :cs10 %><br />
    <%= f.text_field :cs10 %>
  </div>
  <div class="field">
    <%= f.label :cs11 %><br />
    <%= f.text_field :cs11 %>
  </div>
  <div class="field">
    <%= f.label :cs12 %><br />
    <%= f.text_field :cs12 %>
  </div>
  <div class="field">
    <%= f.label :cs13 %><br />
    <%= f.text_field :cs13 %>
  </div>
  <div class="field">
    <%= f.label :cs14 %><br />
    <%= f.text_field :cs14 %>
  </div>
  <div class="field">
    <%= f.label :cs15 %><br />
    <%= f.text_field :cs15 %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<h1>Listing participants</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Passcode</th>
    <th>Sign in count</th>
    <th>Current sign in at</th>
    <th>Last sign in at</th>
    <th>Current sign in ip</th>
    <th>Last sign in ip</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th>Illustration</th>
    <th>Table number</th>
    <th>Session</th>
    <th>Score</th>
    <th>Signature</th>
    <th>Virtual table</th>
    <th>Cs1</th>
    <th>Cs2</th>
    <th>Cs3</th>
    <th>Cs4</th>
    <th>Cs5</th>
    <th>Cs6</th>
    <th>Cs7</th>
    <th>Cs8</th>
    <th>Cs9</th>
    <th>Cs10</th>
    <th>Cs11</th>
    <th>Cs12</th>
    <th>Cs13</th>
    <th>Cs14</th>
    <th>Cs15</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @participants.each do |participant| %>
  <tr>
    <td><%= participant.id %></td>
    <td><%= participant.passcode %></td>
    <td><%= participant.sign_in_count %></td>
    <td><%= participant.current_sign_in_at %></td>
    <td><%= participant.last_sign_in_at %></td>
    <td><%= participant.current_sign_in_ip %></td>
    <td><%= participant.last_sign_in_ip %></td>
    <td><%= participant.created_at %></td>
    <td><%= participant.updated_at %></td>
    <td><img src="<%= participant.illustration %>" alt="<%= participant.name %>"  title="<%= participant.id %>" width="200" length = "200"/></td>
    <td><%= participant.table_number %></td>
    <td><%= participant.session_id %></td>
    <td><%= participant.score %></td>
    <td><%= participant.signature %></td>
    <td><%= participant.virtual_table_id %></td>
    <td><%= participant.cs1 %></td>
    <td><%= participant.cs2 %></td>
    <td><%= participant.cs3 %></td>
    <td><%= participant.cs4 %></td>
    <td><%= participant.cs5 %></td>
    <td><%= participant.cs6 %></td>
    <td><%= participant.cs7 %></td>
    <td><%= participant.cs8 %></td>
    <td><%= participant.cs9 %></td>
    <td><%= participant.cs10 %></td>
    <td><%= participant.cs11 %></td>
    <td><%= participant.cs12 %></td>
    <td><%= participant.cs13 %></td>
    <td><%= participant.cs14 %></td>
    <td><%= participant.cs15 %></td>
    <td><%= participant.first_name %></td>
    <td><%= participant.last_name %></td>
    <td><%= participant.name %></td>
    <td><%= participant.email %></td>
    <td><%= link_to 'Show', participant %></td>
    <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
    <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<h1>New participant</h1>

<%= render 'form' %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @participant.id %>
</p>

<p>
  <b>Passcode:</b>
  <%= @participant.passcode %>
</p>

<p>
  <b>Sign in count:</b>
  <%= @participant.sign_in_count %>
</p>

<p>
  <b>Current sign in at:</b>
  <%= @participant.current_sign_in_at %>
</p>

<p>
  <b>Last sign in at:</b>
  <%= @participant.last_sign_in_at %>
</p>

<p>
  <b>Current sign in ip:</b>
  <%= @participant.current_sign_in_ip %>
</p>

<p>
  <b>Last sign in ip:</b>
  <%= @participant.last_sign_in_ip %>
</p>

<p>
  <b>Created at:</b>
  <%= @participant.created_at %>
</p>

<p>
  <b>Updated at:</b>
  <%= @participant.updated_at %>
</p>

<p>
  <b>Illustration:</b>
  <%= @participant.illustration %>
</p>

<p>
  <b>Table number:</b>
  <%= @participant.table_number %>
</p>

<p>
  <b>Session:</b>
  <%= @participant.session_id %>
</p>

<p>
  <b>Score:</b>
  <%= @participant.score %>
</p>

<p>
  <b>Signature:</b>
  <%= @participant.signature %>
</p>

<p>
  <b>Virtual table:</b>
  <%= @participant.virtual_table_id %>
</p>

<p>
  <b>Cs1:</b>
  <%= @participant.cs1 %>
</p>

<p>
  <b>Cs2:</b>
  <%= @participant.cs2 %>
</p>

<p>
  <b>Cs3:</b>
  <%= @participant.cs3 %>
</p>

<p>
  <b>Cs4:</b>
  <%= @participant.cs4 %>
</p>

<p>
  <b>Cs5:</b>
  <%= @participant.cs5 %>
</p>

<p>
  <b>Cs6:</b>
  <%= @participant.cs6 %>
</p>

<p>
  <b>Cs7:</b>
  <%= @participant.cs7 %>
</p>

<p>
  <b>Cs8:</b>
  <%= @participant.cs8 %>
</p>

<p>
  <b>Cs9:</b>
  <%= @participant.cs9 %>
</p>

<p>
  <b>Cs10:</b>
  <%= @participant.cs10 %>
</p>

<p>
  <b>Cs11:</b>
  <%= @participant.cs11 %>
</p>

<p>
  <b>Cs12:</b>
  <%= @participant.cs12 %>
</p>

<p>
  <b>Cs13:</b>
  <%= @participant.cs13 %>
</p>

<p>
  <b>Cs14:</b>
  <%= @participant.cs14 %>
</p>

<p>
  <b>Cs15:</b>
  <%= @participant.cs15 %>
</p>

<p>
  <b>First name:</b>
  <%= @participant.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @participant.last_name %>
</p>

<p>
  <b>Name:</b>
  <%= @participant.name %>
</p>

<p>
  <b>Email:</b>
  <%= @participant.email %>
</p>


<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>